import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import {
  ActivityIndicator,
  FlatList,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import AutoGeneratedSection from '../../components/AutoGeneratedSection';
import LikedSongsModal from '../../components/LikedSongsModal';
import MiniPlayer from '../../components/MiniPlayer';
import PlaylistModal from '../../components/PlaylistModal';
import WaveformBars from '../../components/WaveformBars';
import { C } from '../../constants/theme';
import { AutoPlaylist, useWavesSongs, WavePlaylist } from '../../hooks/useWavesSongs';
import { usePlayer } from '../../store/playerStore';

const sectionLabel = {
  fontSize: 9,
  letterSpacing: 1.2,
  fontWeight: '600' as const,
  color: C.textMuted,
  marginHorizontal: 16,
  marginBottom: 12,
};

function SkeletonRow() {
  return (
    <View
      style={ {
        backgroundColor: C.card,
        borderWidth: 0.5,
        borderColor: C.border,
        borderRadius: 14,
        padding: 12,
        marginHorizontal: 16,
        marginVertical: 5,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
      } }
    >
      <View style={ { width: 32, height: 32, backgroundColor: '#1e1e2e', borderRadius: 8 } } />
      <View style={ { flex: 1, gap: 6 } }>
        <View style={ { height: 10, backgroundColor: '#1e1e2e', borderRadius: 5, width: '70%' } } />
        <View style={ { height: 8, backgroundColor: '#1a1a28', borderRadius: 5, width: '40%' } } />
      </View>
    </View>
  );
}

export default function WavesScreen() {
  const insets = useSafeAreaInsets();
  const { likedSongs } = usePlayer();
  const { playlists, autoPlaylists, loading } = useWavesSongs();

  const [likedModalVisible, setLikedModalVisible] = useState(false);
  const [selectedPlaylist, setSelectedPlaylist] = useState<WavePlaylist | AutoPlaylist | null>(null);
  const [playlistModalVisible, setPlaylistModalVisible] = useState(false);

  const openPlaylist = (playlist: WavePlaylist | AutoPlaylist) => {
    setSelectedPlaylist(playlist);
    setPlaylistModalVisible(true);
  };

  return (
    <View style={ { flex: 1, backgroundColor: C.bg } }>
      <FlatList
        data={ playlists }
        keyExtractor={ (item) => item.id }
        showsVerticalScrollIndicator={ false }
        ListHeaderComponent={
          <View style={ { paddingTop: insets.top + 16 } }>

            {/* ── Title ── */ }
            <Text style={ { fontSize: 19, fontWeight: '500', color: C.text, marginHorizontal: 16, marginBottom: 20 } }>
              Your waves
            </Text>

            {/* ── Liked Songs ── */ }
            <Text style={ sectionLabel }>PINNED</Text>
            <TouchableOpacity
              activeOpacity={ 0.8 }
              onPress={ () => setLikedModalVisible(true) }
              style={ {
                backgroundColor: C.card,
                borderWidth: 0.5,
                borderColor: C.border,
                borderRadius: 14,
                padding: 14,
                marginHorizontal: 16,
                marginBottom: 8,
                flexDirection: 'row',
                alignItems: 'center',
                gap: 12,
              } }
            >
              <WaveformBars color={ C.purple } bg={ C.purpleDim } count={ 5 } size="md" />
              <View style={ { flex: 1 } }>
                <Text style={ { fontSize: 14, fontWeight: '500', color: C.text, marginBottom: 3 } }>
                  Liked Songs
                </Text>
                <Text style={ { fontSize: 11, color: C.textMuted } }>
                  { likedSongs.length > 0
                    ? `${likedSongs.length} ${likedSongs.length === 1 ? 'song' : 'songs'}`
                    : 'No liked songs yet' }
                </Text>
              </View>
              <Text style={ { fontSize: 18, color: likedSongs.length > 0 ? C.purple : C.textDim } }>
                { likedSongs.length > 0 ? '♥' : '♡' }
              </Text>
            </TouchableOpacity>

            {/* ── My Playlists ── */ }
            <Text style={ { ...sectionLabel, marginTop: 20 } }>MY PLAYLISTS</Text>
          </View>
        }

        renderItem={ ({ item }) =>
          loading ? (
            <SkeletonRow />
          ) : (
            <TouchableOpacity
              onPress={ () => openPlaylist(item) }
              activeOpacity={ 0.8 }
              style={ {
                backgroundColor: C.card,
                borderWidth: 0.5,
                borderColor: C.border,
                borderRadius: 14,
                padding: 12,
                marginHorizontal: 16,
                marginVertical: 5,
                flexDirection: 'row',
                alignItems: 'center',
                gap: 12,
              } }
            >
              <WaveformBars color={ item.color } bg={ item.bg } count={ 5 } size="sm" />
              <View style={ { flex: 1 } }>
                <Text style={ { fontSize: 13, fontWeight: '500', color: C.text, marginBottom: 4 } }>
                  { item.name }
                </Text>
                <View style={ { flexDirection: 'row', gap: 8, marginBottom: 5 } }>
                  <Text style={ { fontSize: 10, color: C.textMuted } }>
                    { item.songs.length > 0 ? `${item.songs.length} songs` : 'No songs found' }
                  </Text>
                  <Text style={ { fontSize: 10, color: C.textMuted } }>{ item.duration }</Text>
                </View>
                <View style={ { flexDirection: 'row', gap: 5, flexWrap: 'wrap' } }>
                  { item.tags.map((tag) => (
                    <Text
                      key={ tag }
                      style={ {
                        fontSize: 9,
                        color: C.textMuted,
                        backgroundColor: C.border,
                        paddingHorizontal: 8,
                        paddingVertical: 3,
                        borderRadius: 10,
                      } }
                    >
                      { tag }
                    </Text>
                  )) }
                </View>
              </View>
              <Text style={ { fontSize: 18, color: C.textDim } }>›</Text>
            </TouchableOpacity>
          )
        }

        ListFooterComponent={
          <AutoGeneratedSection
            autoPlaylists={ autoPlaylists }
            loading={ loading }
            onPress={ openPlaylist }
          />
        }
      />

      {/* ── Modals ── */ }
      <LikedSongsModal
        visible={ likedModalVisible }
        onClose={ () => setLikedModalVisible(false) }
      />

      <PlaylistModal
        playlist={ selectedPlaylist }
        visible={ playlistModalVisible }
        onClose={ () => setPlaylistModalVisible(false) }
      />

      <MiniPlayer />
    </View>
  );
}