import { useRouter } from 'expo-router';
import React from 'react';
import {
    FlatList,
    ScrollView,
    Text,
    TouchableOpacity,
    View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import MiniPlayer from '../../components/MiniPlayer';
import WaveformBars from '../../components/WaveformBars';
import { PLAYLISTS } from '../../constants/mockData';
import { C } from '../../constants/theme';

const autoGenerated = [
  { id: '1', name: 'Time capsule', count: 42, color: C.pink, bg: C.pinkDim },
  { id: '2', name: 'Mood mix', count: 38, color: C.amber, bg: C.amberDim },
  { id: '3', name: 'Deep cuts', count: 156, color: C.purple, bg: C.purpleDim },
];

const sectionLabel = {
  fontSize: 9,
  letterSpacing: 1.2,
  fontWeight: '600' as const,
  color: C.textMuted,
  marginHorizontal: 16,
  marginBottom: 12,
};

export default function WavesScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();

  return (
    <View style={{ flex: 1, backgroundColor: C.bg }}>
      <FlatList
        data={PLAYLISTS}
        keyExtractor={(item) => item.id}
        showsVerticalScrollIndicator={false}
        ListHeaderComponent={
          <View style={{ paddingTop: insets.top + 16 }}>

            {/* ── Page title ── */}
            <Text
              style={{
                fontSize: 19,
                fontWeight: '500',
                color: C.text,
                marginHorizontal: 16,
                marginBottom: 20,
              }}
            >
              Your waves
            </Text>

            {/* ── Pinned label ── */}
            <Text style={sectionLabel}>PINNED</Text>

            {/* ── Liked Songs card ── */}
            <TouchableOpacity
              activeOpacity={0.8}
              style={{
                backgroundColor: C.card,
                borderWidth: 0.5,
                borderColor: C.border,
                borderRadius: 14,
                padding: 14,
                marginHorizontal: 16,
                marginBottom: 8,
                flexDirection: 'row',
                alignItems: 'center',
                gap: 12,
              }}
            >
              <WaveformBars color={C.purple} bg={C.purpleDim} count={5} size="md" />
              <View style={{ flex: 1 }}>
                <Text style={{ fontSize: 14, fontWeight: '500', color: C.text, marginBottom: 3 }}>
                  Liked Songs
                </Text>
                <Text style={{ fontSize: 11, color: C.textMuted }}>214 songs</Text>
              </View>
              <Text style={{ fontSize: 18, color: C.purple }}>♥</Text>
            </TouchableOpacity>

            {/* ── My Playlists label ── */}
            <Text style={{ ...sectionLabel, marginTop: 20 }}>MY PLAYLISTS</Text>
          </View>
        }

        renderItem={({ item }) => (
          <TouchableOpacity
            onPress={() => router.push(`/playlist/${item.id}`)}
            activeOpacity={0.8}
            style={{
              backgroundColor: C.card,
              borderWidth: 0.5,
              borderColor: C.border,
              borderRadius: 14,
              padding: 12,
              marginHorizontal: 16,
              marginVertical: 5,
              flexDirection: 'row',
              alignItems: 'center',
              gap: 12,
            }}
          >
            <WaveformBars color={item.color} bg={item.bg} count={5} size="sm" />

            <View style={{ flex: 1 }}>
              <Text style={{ fontSize: 13, fontWeight: '500', color: C.text, marginBottom: 4 }}>
                {item.name}
              </Text>

              {/* count + duration */}
              <View style={{ flexDirection: 'row', gap: 8, marginBottom: 5 }}>
                <Text style={{ fontSize: 10, color: C.textMuted }}>{item.count} songs</Text>
                <Text style={{ fontSize: 10, color: C.textMuted }}>{item.duration}</Text>
              </View>

              {/* tags */}
              <View style={{ flexDirection: 'row', gap: 5, flexWrap: 'wrap' }}>
                {item.tags.map((tag) => (
                  <Text
                    key={tag}
                    style={{
                      fontSize: 9,
                      color: C.textMuted,
                      backgroundColor: C.border,
                      paddingHorizontal: 8,
                      paddingVertical: 3,
                      borderRadius: 10,
                    }}
                  >
                    {tag}
                  </Text>
                ))}
              </View>
            </View>

            <Text style={{ fontSize: 18, color: C.textDim }}>›</Text>
          </TouchableOpacity>
        )}

        ListFooterComponent={
          <View style={{ paddingBottom: 120 }}>

            {/* ── Auto-generated label ── */}
            <Text style={{ ...sectionLabel, marginTop: 24 }}>AUTO-GENERATED</Text>

            {/* ── Horizontal scroll ── */}
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={{ paddingHorizontal: 16, gap: 10 }}
            >
              {autoGenerated.map((item) => (
                <TouchableOpacity
                  key={item.id}
                  activeOpacity={0.8}
                  style={{
                    backgroundColor: item.bg,
                    borderWidth: 0.5,
                    borderColor: C.border,
                    borderRadius: 14,
                    padding: 14,
                    alignItems: 'center',
                    width: 116,
                    gap: 8,
                  }}
                >
                  <WaveformBars color={item.color} bg="transparent" count={4} size="sm" />
                  <Text
                    style={{
                      fontSize: 11,
                      fontWeight: '500',
                      color: C.text,
                      textAlign: 'center',
                    }}
                  >
                    {item.name}
                  </Text>
                  <Text style={{ fontSize: 9, color: C.textMuted }}>
                    {item.count} songs
                  </Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
        }
      />

      {/* ── Mini Player ── */}
      <View style={{ position: 'static', bottom: 50, left: 0, right: 0 }}>
        <MiniPlayer />
      </View>
    </View>
  );
}