import React from 'react';
import { ScrollView, Text, TouchableOpacity, View } from 'react-native';
import WaveformBars from './WaveformBars';
import { C } from '../constants/theme';
import { AutoPlaylist } from '../hooks/useWavesSongs';

interface Props {
    autoPlaylists: AutoPlaylist[];
    loading: boolean;
    onPress: (playlist: AutoPlaylist) => void;
}

function SkeletonAutoCard() {
    return (
        <View
            style={ {
                backgroundColor: C.card,
                borderWidth: 0.5,
                borderColor: C.border,
                borderRadius: 14,
                padding: 14,
                width: 116,
                gap: 8,
                alignItems: 'center',
            } }
        >
            <View style={ { width: 32, height: 32, backgroundColor: '#1e1e2e', borderRadius: 8 } } />
            <View style={ { height: 9, width: '80%', backgroundColor: '#1e1e2e', borderRadius: 4 } } />
            <View style={ { height: 7, width: '50%', backgroundColor: '#1a1a28', borderRadius: 4 } } />
        </View>
    );
}

export default function AutoGeneratedSection({ autoPlaylists, loading, onPress }: Props) {
    return (
        <View style={ { paddingBottom: 120 } }>
            <Text
                style={ {
                    fontSize: 9,
                    letterSpacing: 1.2,
                    fontWeight: '600',
                    color: C.textMuted,
                    marginHorizontal: 16,
                    marginBottom: 12,
                    marginTop: 24,
                } }
            >
                AUTO-GENERATED
            </Text>

            <ScrollView
                horizontal
                showsHorizontalScrollIndicator={ false }
                contentContainerStyle={ { paddingHorizontal: 16, gap: 10 } }
            >
                { loading
                    ? [1, 2, 3].map((i) => <SkeletonAutoCard key={ i } />)
                    : autoPlaylists.map((item) => (
                        <TouchableOpacity
                            key={ item.id }
                            activeOpacity={ 0.8 }
                            onPress={ () => onPress(item) }
                            style={ {
                                backgroundColor: item.bg,
                                borderWidth: 0.5,
                                borderColor: C.border,
                                borderRadius: 14,
                                padding: 14,
                                alignItems: 'center',
                                width: 116,
                                gap: 8,
                            } }
                        >
                            <WaveformBars color={ item.color } bg="transparent" count={ 4 } size="sm" />
                            <Text style={ { fontSize: 11, fontWeight: '500', color: C.text, textAlign: 'center' } }>
                                { item.name }
                            </Text>
                            <Text style={ { fontSize: 9, color: C.textMuted } }>
                                { item.songs.length > 0 ? `${item.songs.length} songs` : '...' }
                            </Text>
                        </TouchableOpacity>
                    )) }
            </ScrollView>
        </View>
    );
}