import { usePlayer } from '@/store/playerStore';
import { useRouter } from 'expo-router';
import React from 'react';
import {
    FlatList,
    ScrollView,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import MiniPlayer from '../../components/MiniPlayer';
import WaveformBars from '../../components/WaveformBars';
import { PLAYLISTS } from '../../constants/mockData';
import { C } from '../../constants/theme';

const autoGenerated = [
  { id: '1', name: 'Time capsule', count: 42, color: C.pink, bg: C.pinkDim },
  { id: '2', name: 'Mood mix', count: 38, color: C.amber, bg: C.amberDim },
  { id: '3', name: 'Deep cuts', count: 156, color: C.purple, bg: C.purpleDim },
];

export default function WavesScreen() {
  const insets = useSafeAreaInsets();
  const { song, isPlaying, toggle } = usePlayer();
  const router = useRouter();
  

  const handlePlaylistPress = (id: string) => {
    router.push(`/playlist/${id}`);
  };

  return (
    <View style={[styles.container, { backgroundColor: C.bg }]}>
      <FlatList
        data={PLAYLISTS}
        keyExtractor={(item) => item.id}
        scrollEnabled
        ListHeaderComponent={
          <View style={{ paddingTop: insets.top + 16 }}>
            <Text style={[styles.sectionLabel, { color: C.textMuted }]}>
              PINNED
            </Text>
            <TouchableOpacity
              style={[
                styles.likedCard,
                {
                  backgroundColor: C.card,
                  borderColor: C.border,
                },
              ]}
              activeOpacity={0.8}
            >
              <WaveformBars color={C.purple} bg={C.purpleDim} size="md" />
              <View style={styles.likedInfo}>
                <Text style={[styles.likedTitle, { color: C.text }]}>Liked Songs</Text>
                <Text style={[styles.likedCount, { color: C.textMuted }]}>214 songs</Text>
              </View>
              <Text style={{ fontSize: 18 }}>♡</Text>
            </TouchableOpacity>

            <Text style={[styles.sectionLabel, { color: C.textMuted, marginTop: 24 }]}>
              MY PLAYLISTS
            </Text>
          </View>
        }
        renderItem={({ item }) => (
          <TouchableOpacity
            onPress={() => handlePlaylistPress(item.id)}
            style={[
              styles.playlistRow,
              {
                backgroundColor: C.card,
                borderColor: C.border,
              },
            ]}
            activeOpacity={0.8}
          >
            <WaveformBars color={item.color} bg={item.bg} size="sm" />
            <View style={styles.playlistInfo}>
              <Text style={[styles.playlistName, { color: C.text }]}>
                {item.name}
              </Text>
              <View style={styles.playlistMeta}>
                <Text style={[styles.playlistCount, { color: C.textMuted }]}>
                  {item.count} songs
                </Text>
                <Text style={[styles.playlistDuration, { color: C.textMuted }]}>
                  {item.duration}
                </Text>
              </View>
              <View style={styles.tagContainer}>
                {item.tags.map((tag) => (
                  <Text
                    key={tag}
                    style={[
                      styles.tag,
                      {
                        backgroundColor: C.border,
                        color: C.textMuted,
                      },
                    ]}
                  >
                    {tag}
                  </Text>
                ))}
              </View>
            </View>
            <Text style={{ fontSize: 16, color: C.textMuted }}>›</Text>
          </TouchableOpacity>
        )}
        ListFooterComponent={
          <View>
            <Text style={[styles.sectionLabel, { color: C.textMuted, marginTop: 24 }]}>
              AUTO-GENERATED
            </Text>
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.autoGenContent}
            >
              {autoGenerated.map((item) => (
                <TouchableOpacity
                  key={item.id}
                  style={[
                    styles.autoGenCard,
                    {
                      backgroundColor: C.card,
                      borderColor: C.border,
                    },
                  ]}
                  activeOpacity={0.8}
                >
                  <WaveformBars color={item.color} bg={item.bg} size="sm" />
                  <Text style={[styles.autoGenName, { color: C.text }]}>
                    {item.name}
                  </Text>
                  <Text style={[styles.autoGenCount, { color: C.textMuted }]}>
                    {item.count}
                  </Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
            <View style={{ height: 100 }} />
          </View>
        }
      />
      <View style={styles.miniPlayerWrapper}>
        <MiniPlayer />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  sectionLabel: {
    fontSize: 9,
    letterSpacing: 1,
    marginHorizontal: 16,
    marginBottom: 12,
    fontWeight: '600',
  },
  likedCard: {
    borderWidth: 0.5,
    borderRadius: 14,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  likedInfo: {
    flex: 1,
  },
  likedTitle: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 2,
  },
  likedCount: {
    fontSize: 11,
  },
  playlistRow: {
    borderWidth: 0.5,
    borderRadius: 14,
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  playlistInfo: {
    flex: 1,
  },
  playlistName: {
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 4,
  },
  playlistMeta: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 4,
  },
  playlistCount: {
    fontSize: 10,
  },
  playlistDuration: {
    fontSize: 10,
  },
  tagContainer: {
    flexDirection: 'row',
    gap: 4,
    flexWrap: 'wrap',
  },
  tag: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    fontSize: 9,
  },
  autoGenContent: {
    paddingHorizontal: 16,
    paddingRight: 32,
  },
  autoGenCard: {
    borderWidth: 0.5,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    marginRight: 12,
    width: 110,
  },
  autoGenName: {
    fontSize: 11,
    fontWeight: '500',
    marginTop: 8,
    textAlign: 'center',
  },
  autoGenCount: {
    fontSize: 9,
    marginTop: 2,
  },
  miniPlayerWrapper: {
    position: 'absolute',
    bottom: 50,
    left: 0,
    right: 0,
  },
});
